  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s"  .Values.env .Values.security.name}}
  labels:
    app.kubernetes.io/name: {{ printf "%s-%s"  .Values.env .Values.security.name}}
    helm.sh/chart: {{ include "semoss.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.security.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{printf "%s-%s"  .Values.env .Values.security.name}}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{printf "%s-%s"  .Values.env .Values.security.name}}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{printf "%s-%s"  .Values.env .Values.security.name}}
          image: "{{ .Values.security.image.repository }}:{{ .Values.security.image.tag }}"
          imagePullPolicy: {{ .Values.security.image.pullPolicy }}
          ports:
          - containerPort: {{.Values.security.service.port}}
